In [ ]:
import numpy as np

create numpy array using int and float datatype

In [ ]:
f = np.array([[1,2,3],[4,5,6]], dtype=np.float32)
i = np.array([[1,2,3],[4,5,6]], dtype=int)

print(f)
print()
print(i)

[[1. 2. 3.]
 [4. 5. 6.]]

[[1 2 3]
 [4 5 6]]


create arrays with 0,1,2,3,4 dimensions and print shape and dimensions of created arrays

In [ ]:
zero = np.zeros(0)
one = np.zeros((1))
two = np.zeros((2,2))
three = np.zeros((3,3,3))
four = np.zeros((4,4,4,4))

print("shape")
print(zero.shape)
print(one.shape)
print(two.shape)
print(three.shape)
print(four.shape)
print()
print("dimensions")
print(zero.ndim)
print(one.ndim)
print(two.ndim)
print(three.ndim)
print(four.ndim)

shape
(0,)
(1,)
(2, 2)
(3, 3, 3)
(4, 4, 4, 4)

dimensions
1
1
2
3
4


create 2x2 3x3 4x4 identity matrix

In [ ]:
twoBYtwo = np.eye(2,dtype=int)
threeBYthree = np.eye(3,dtype=int)
fourBYfour = np.eye(4,dtype=int)

print(twoBYtwo)
print()
print(threeBYthree)
print()
print(fourBYfour)

[[1 0]
 [0 1]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


2x5 with all 0 elements

In [ ]:
np.zeros((2,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

3x5 with all elements = 5

In [ ]:
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

random integers from 0-100 with sample size 25

In [ ]:
np.random.randint(0,100,(5,5))

array([[41, 76, 19, 12, 13],
       [55, 51, 96, 56, 59],
       [94, 15, 39, 32, 53],
       [97, 49,  2, 76, 56],
       [64, 25, 30, 96, 63]])

3x3 with elements = 1

In [ ]:
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

2x3 with random b/w 1-100 and then reshape it into 3x2

In [ ]:
a = np.random.randint(0,100,(2,3))
a.reshape(3,2)
a

array([[72,  1, 85],
       [68, 40, 55]])

random from 0-1000 and size 50

perform the following operations

1 print first 10 elements

2 last 10

3 from 0 to 25

4 at index 22

5 last 10 using -ve index



In [ ]:
a = np.random.randint(0,1000,(50))

print(a[0:10])
print()
print(a[40:51])
print()
print(a[0:25])
print()
print(a[22])
print()
print(a[-10:-1])

[856 378 811 581  99 656 395 894 383  54]

[885 893 403 632 462 832 293 673 151 318]

[856 378 811 581  99 656 395 894 383  54 448 636 512 123   8 473  29 482
 256 529 206 711  13 787 106]

13

[885 893 403 632 462 832 293 673 151]


a = [1,2,3,4,5]

insert 6 at end

insert 10 at start

30 before 4

update 5 = 50

delete 50

search for 30

sort

In [ ]:
a = np.array([1,2,3,4,5])
a = np.append(a,6)
print(a)
print()
a = np.insert(a,0,10)
print(a)
print()
a = np.insert(a,4,30)
print(a)
print()
a[a==5] = 50
print(a)
print()
a = np.delete(a, a==50)
print(a)
print()
x = np.where(a==30)
print(x)
print()
a = np.sort(a)
print(a)

[1 2 3 4 5 6]

[10  1  2  3  4  5  6]

[10  1  2  3 30  4  5  6]

[10  1  2  3 30  4 50  6]

[10  1  2  3 30  4  6]

(array([4]),)

[ 1  2  3  4  6 10 30]


In [ ]:
a = np.random.randint(2,70,(2,4))
b = np.random.randint(2,70,(4,2))
print(a)
print()
print(b)
print()
np.dot(a,b)

[[44 34 57 64]
 [38 42 50 12]]

[[11 30]
 [12 34]
 [10 34]
 [59 69]]



array([[5238, 8830],
       [2130, 5096]])

a = [1,2,3,4]
b = [5,6,7,8]


---


add a,b
subtract a,b
multiply with 1)5 2)eachother

---

divide 1)by 2 

2)a with b 

3)b with a

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a+b)
print()
print(a-5)
print()
print(b-5)
print()
print(b-a)
print()
print(f'a/2 = {a/2}')
print()
print(f'b/2 = {b/2}')
print()
print(f'a/b = {a/b}')
print()
print(f'b/a = {b/a}')

[ 6  8 10 12]

[-4 -3 -2 -1]

[0 1 2 3]

[4 4 4 4]

a/2 = [0.5 1.  1.5 2. ]

b/2 = [2.5 3.  3.5 4. ]

a/b = [0.2        0.33333333 0.42857143 0.5       ]

b/a = [5.         3.         2.33333333 2.        ]


a = np.array([[2,6],[6,13]])

b = np.array([[1,4],[2,11]])

matrix multiplication of a and b

sqrt of a and b

In [ ]:
a = np.array([[2,6],[6,13]])
b = np.array([[1,4],[2,11]])

print(np.dot(a,b))
print()
print(np.sqrt(a))
print()
print(np.sqrt(b))

[[ 14  74]
 [ 32 167]]

[[1.41421356 2.44948974]
 [2.44948974 3.60555128]]

[[1.         2.        ]
 [1.41421356 3.31662479]]


3x3 with random values and flatten with reshape

In [ ]:
a = np.random.randint(0,1000,(3,3))
np.ndarray.flatten(a)

array([309, 308, 438, 835, 445, 887, 701, 277, 992])

create array with all days of an year using datetime64 numpy module

In [ ]:
a = np.arange(np.datetime64('2023-01-01'),np.datetime64('2023-12-31'))
a


array(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
       '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
       '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
       '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
       '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
       '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
       '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
       '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
       '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
       '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
       '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13',
       '2023-02-14', '2023-02-15', '2023-02-16', '2023-02-17',
       '2023-02-18', '2023-02-19', '2023-02-20', '2023-02-21',
       '2023-02-22', '2023-02-23', '2023-02-24', '2023-02-25',
       '2023-02-26', '2023-02-27', '2023-02-28', '2023-03-01',
       '2023-03-02', '2023-03-03', '2023-03-04', '2023-

In [ ]:
np.log(2.718)

0.999896315728952

In [ ]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.linspace(0,10,11,dtype=int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.random.random((3,3))

array([[0.73224997, 0.50583589, 0.91240144],
       [0.80589148, 0.5182967 , 0.71484021],
       [0.48051761, 0.55907876, 0.36653385]])

a = np.array([[2,3],[6,4]])

b = np.array([[3,6],[4,9]])]])

perform horizontal, vertical, row, cloumn and depth stacking

append a to b

concatenate a and b

In [ ]:
a = np.array([[2,3],[6,4]],dtype=int)
b = np.array([[3,6],[4,9]],dtype=int)

h = np.hstack((a,b))
v = np.vstack((a,b))
r = np.row_stack((a,b))
c = np.column_stack((a,b))
d = np.dstack((a,b))
print(h)
print()
print(v)
print()
print(r)
print()
print(c)
print()
print(d)
print()
print(np.concatenate((b,a),axis=None))
print()
print(np.append(a,b))

[[2 3 3 6]
 [6 4 4 9]]

[[2 3]
 [6 4]
 [3 6]
 [4 9]]

[[2 3]
 [6 4]
 [3 6]
 [4 9]]

[[2 3 3 6]
 [6 4 4 9]]

[[[2 3]
  [3 6]]

 [[6 4]
  [4 9]]]

[3 6 4 9 2 3 6 4]

[2 3 6 4 3 6 4 9]


horizontal and vertical split

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])

print(np.hsplit(a,3))
print()
print(np.vsplit(a,6))
print()

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]])]



find rank,trace,inverse,transpose,det, eigenvalues and vectors

In [103]:
from numpy import linalg as la
a = ([[1,4,7],[3,1,9],[2,8,11]])
print(la.matrix_rank(a))
print()
print(np.trace(a))
print()
print(la.inv(a))
print()
print(np.transpose(a))
print()
print(la.det(a))
print()
print(la.eig(a))

3

13

[[-1.84848485  0.36363636  0.87878788]
 [-0.45454545 -0.09090909  0.36363636]
 [ 0.66666667  0.         -0.33333333]]

[[ 1  3  2]
 [ 4  1  8]
 [ 7  9 11]]

33.000000000000014

(array([17.41535066, -0.48171173, -3.93363893]), array([[-0.44018011, -0.89954986,  0.05526996],
       [-0.49219026, -0.26902919, -0.88319891],
       [-0.75099282,  0.34414147,  0.46573052]]))


find correlation coefficient

In [108]:
a = np.array([[11,17,42],[21,19,27]])
b = np.array([[12,44,39],[62,81,10]])

np.corrcoef(a,b)

array([[ 1.        ,  0.9106039 ,  0.53232532, -0.90264562],
       [ 0.9106039 ,  1.        ,  0.13487934, -0.99982205],
       [ 0.53232532,  0.13487934,  1.        , -0.11616343],
       [-0.90264562, -0.99982205, -0.11616343,  1.        ]])

 Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return [ [5, 5, 5], [5, 5, 5], [5, 5, 5] ]

In [111]:
def fill(size, value):
  a = np.full((size),value)
  return a

fill((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

Create a method that takes n Numpy arrays of same dimensions sums them and return the answer.

In [145]:
def sum_array(*arrays):
  shape = arrays[0].shape
  result = np.zeros(shape,dtype=int)
  for array in arrays:
    result += array
  return result

sum_array(np.array((1,2,3)),np.array((1,2,3)),np.array((1,2,3)))

array([3, 6, 9])

Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two numbers N and M. The method should return the top-left N X M sub matrix e.g: [ [1, 2, 3], [4, 5, 6], [7, 8, 9], ] top_left_sub_matrix (matrix, 2, 2) -> should return: [ [1, 2] [4, 5] ]

In [129]:
def top(matrix,n,m):
  return matrix[:n,:m]

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
top(a,2,2)

array([[1, 2],
       [4, 5]])

Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two numbers N and M The method should return the bottom-right N X M sub matrix e.g.: [ [1, 2, 3], [4, 5, 6], [7, 8, 9], ] sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed) [ [5, 6] [8, 9] ]

In [131]:
def sub(matrix,n,m):
  return matrix[n:,m:]

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub(a,1,1)

array([[5, 6],
       [8, 9]])

Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's standard deviation as values: [1, 1, 1] solution(arr) -> should return : {'mean': 1.0, 'std_dev': 0.0} 

In [133]:
def mean_std(array):
  dict = {"mean":np.mean(array),"std_dev":np.std(array)}
  return dict

a = np.array((1,1,1))
mean_std(a)

{'mean': 1.0, 'std_dev': 0.0}